# Continuous Integration Configuration

name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup CMake
        uses: lukka/get-cmake@v2.0.1

      - name: Configure and Build
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/OAuth2Backend/build/conan_toolchain.cmake .
          cmake --build .

      - name: Test
        run: |
          ctest --timeout 300
        timeout-minutes: 30